sudo: false
dist: trusty

language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "tigefa@gmail.com"
        api_key: $NPM_API_KEY
        gem: travis-build-stages-demo
        on: deploy-npm-release
